### ISSUE TITLE
handle users changing deviceid against same wcgid

### ISSUE THREAD

**Issue by ghobson2013** [boid-com/boidValidator#4]
Currently getRVNWork cronjob does not handle a user deleting their device and registering a new one against the same WCGID. The deviceID is unique in the postgres DB so it throws the following error:
```
Error: A unique constraint would be violated on Device. Details: Field name = wcgid: {"response":{"data":null,"errors":[{"locations":[{"line":1,"column":16}],"path
":["upsertDevice"],"code":3010,"message":"A unique constraint would be violated on Device. Details: Field name = wcgid","requestId":"local:cjzz4x0bqqjlb0785bz26sw7f"}],"status":200},"request":{"query":"
     mutation{upsertDevice(        where:{rvnid:\"cjzyc9k0msbrm0760jrnwvv58\"}         update:{wcgid:\"5053509\"}        create:{ wcgid:\"5053509\" rvnid:\"cjzyc9k0msbrm0760jrnwvv58\"}      ){id}}"}}
```

The ingest just needs extra checks.

**Comment by ghobson2013** [comment]
I now see 8 devices with this issue, it seems to be growing..

08:54:57.573 [ERROR getDevices] [Error: A unique constraint would be violated on Device. Details: Field name = wcgid: {"response":{"data":null,"errors":[{"locations":[{"line":1,"column":16}],"path":["upsertDevice"],"code":3010,"message":"A unique constraint would be violated on Device. Details: Field name = wcgid","requestId":"local:ck0dln7z3nvqx0784qxex3zek"}],"status":200},"request":{"query":"      mutation{upsertDevice(        where:{rvnid:\"ck041z9j4880x0760wg0rl2d6\"}         update:{wcgid:\"5245567\"}        create:{ wcgid:\"5245567\" rvnid:\"ck041z9j4880x0760wg0rl2d6\"}      ){id}}"}}]

**Comment by boid-com** [comment]
This should be handled automatically
