### ISSUE TITLE
configure logdir destination and logrotation for pm2 logs

### ISSUE THREAD

**Issue by ghobson2013** [boid-com/boidValidator#6]
In production i recommend we log pm2 cron output to /var/log/pm2 instead of ~/.pm2/log
and that we add them to /etc/logrotate.d so they don't grow very large.

**Comment by ghobson2013** [comment]
I would start pm2 with the -l /var/log/pm2  option
```
-l --log [path]              specify filepath to output both out and error logs
```

logrotation can be easily handled as follows:

```
pm2 install pm2-logrotate
pm2 logrotate -u user
```

**Comment by boid-com** [comment]
Maybe we need a "tips and tricks" readme for all this additional information.
